sonar.projectKey=frontend-pet-app
sonar.projectName=Frontend Pet Matcher
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.login=squ_4984d414e6987d0d9c1b3a9f7ce43308de18e7dc
sonar.exclusions=node_modules/**, dist/**, .parcel-cache/**, **/*.test.js

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

